### ISSUE TITLE
Updated package to 7.0.0

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core.mysql#1]
We're hoping to release the official release for `7.0` end of next week. When the packages goes live it would be great if the MySql package would be updated as well. It's already possible to test against the `rc1` packages.

Regards

**Comment by aatmmr** [comment]
I totally agree and will take care of the update, however, are unable to work on it until the end of week 34.

**Comment by tidyui** [comment]
As soon as it's tested against `7.0` I can roll out the new package. Also @aatmmr, do you have an account on NuGet so I can add you as owner of the package giving you rights to push new versions?

**Comment by aatmmr** [comment]
I just pushed the branch with the changes. It was tested with the MvcWeb from the master branch of the core project and appeared to work flawlessly. I don't have an NuGet account yet but can set up one.

**Comment by tidyui** [comment]
Awesome, let me merge it into master and deploy the package!

**Comment by aatmmr** [comment]
You were faster than I 👍

**Comment by tidyui** [comment]
Done! Thanks for your help!!!

**Comment by aatmmr** [comment]
You're welcome and thanks for your work on piranha!
